//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerSelector
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public Players()
        {
            this.PlayerInTeams = new HashSet<PlayerInTeams>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int numberOfGoals { get; set; }
        public int numberOfGames { get; set; }
        public int numberOfPoints { get; set; }
        public double goalRatio { get; set; }
        public double gameRatio { get; set; }
        public double pointRatio { get; set; }
    
        public virtual ICollection<PlayerInTeams> PlayerInTeams { get; set; }
    }
}
